# Generated by Django 3.2.15 on 2023-07-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'торт',
                'verbose_name_plural': 'торты',
            },
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('shape', models.CharField(choices=[('квадрат', 'Квадрат (+600)'), ('круг', 'Круг (+400)'), ('прямоугольник', 'Прямоугольник (+1000)')], max_length=100)),
                ('topping', models.CharField(choices=[('без топпинга', 'Без топпинга (+0)'), ('белый соус', 'Белый соус (+200)'), ('карамельный сироп', 'Карамельный сироп (+180)'), ('кленовый сироп', 'Кленовый сироп (+200)'), ('клубничный сироп', 'Клубничный сироп (+300)'), ('черничный сироп', 'Черничный сироп (+350)'), ('молочный шоколад', 'Молочный шоколад (+200)')], max_length=100)),
                ('berries', models.CharField(blank=True, choices=[('ежевика', 'Ежевика (+400)'), ('малина', 'Малина (+300)'), ('голубика', 'Голубика (+450)'), ('клубника', 'Клубника (+500)')], max_length=100)),
                ('decor', models.CharField(blank=True, choices=[('фисташки', 'Фисташки (+300)'), ('безе', 'Безе (+400)'), ('фундук', 'Фундук (+350)'), ('пекан', 'Пекан (+300)'), ('маршмеллоу', 'Маршмеллоу (+200)'), ('марципан', 'Марципан (+280)')], max_length=100)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'пользовательский торт',
                'verbose_name_plural': 'пользовательские торты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.TimeField(verbose_name='время')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='src.catalogcake')),
                ('custom_cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='src.customcake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='src.user')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
